version: '3'

services:
  mariadb:
    container_name: mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - inception

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress-vol:/var/www/wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    networks:
      - inception
    ports:
      - 9000:9000
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    volumes:
      - wordpress-vol:/var/www/wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 443:443
    restart: on-failure
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/home/vimercie/data/mariadb-vol'
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/home/vimercie/data/wordpress-vol'